package NewjframePackage;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ForgotPassword extends javax.swing.JFrame {

    public ForgotPassword() {
        initComponents();
    }

    public static String capitalizeFirstLetterOnly(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
    //Reset user password
    public boolean forgotPassword() {
        boolean sucess = false;
        String name = capitalizeFirstLetterOnly(txt_name.getText());
        String contact = txt_contact.getText();
        String newPassword = new String(txt_NewPass.getPassword());
        String confirmPassword = new String(txt_NewPassReEnter.getPassword());
        if (name.equals("") || contact.equals("") || newPassword.equals("") || confirmPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter All Credentails");
            return false;
        }
        if (newPassword.length() < 8 || !newPassword.matches(".*[!@#$%^&*(),.?\\\":{}|<>].*")) {
            JOptionPane.showMessageDialog(this, "Password must be 8 characters, alphanumeric, with at least one special character");
            return false;
        }
        try {
            Connection con = NewjframePackage.DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from users where name = ? and contact = ? ");
            pst.setString(1, name);
            pst.setString(2, contact);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (newPassword.equals(confirmPassword)) {
                    PreparedStatement pst1 = con.prepareStatement("update users set password = ? where name = ? and contact = ?");
                    pst1.setString(1, confirmPassword);
                    pst1.setString(2, name);
                    pst1.setString(3, contact);
                    int rowCount = pst1.executeUpdate();
                    if (rowCount > 0) {
                        JOptionPane.showMessageDialog(this, "Password Changed Sucessfully");
                        sucess = true;
                    } else {
                        JOptionPane.showMessageDialog(this, "Password Change Failure");
                        return false;
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "The new password and confirmation password do not match.");
                    return false;
                }

            } else {
                JOptionPane.showMessageDialog(this, "User does not exits");
                return false;
            }
        } catch (HeadlessException | SQLException e) {
            e.getMessage();
        }
        return sucess;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_name = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_contact = new app.bolivia.swing.JCTextField();
        jLabel30 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        jLabel10 = new javax.swing.JLabel();
        lbl_extra = new javax.swing.JLabel();
        txt_NewPassReEnter = new javax.swing.JPasswordField();
        jLabel35 = new javax.swing.JLabel();
        lbl_extra1 = new javax.swing.JLabel();
        txt_NewPass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setBackground(new java.awt.Color(0, 153, 153));
        txt_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_name.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txt_name.setPlaceholder("Enter Username....");
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 240, 40));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewjframePackage/forgot-password (4).png"))); // NOI18N
        jLabel13.setText("Forgot Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 50));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESET  YOUR  PASSWORD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 280, 20));

        jLabel32.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewjframePackage/icons8_Account_50px.png"))); // NOI18N
        jLabel32.setMaximumSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 40, 60));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewjframePackage/icons8_Secure_50px.png"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 50, 50));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Confirm Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 130, 20));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Mobile no.");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 80, 30));

        txt_contact.setBackground(new java.awt.Color(0, 153, 153));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txt_contact.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_contact.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txt_contact.setPlaceholder("Enter mobile number...");
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        jPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 240, 40));

        jLabel30.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewjframePackage/icons8_Google_Mobile_50px.png"))); // NOI18N
        jLabel30.setMaximumSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 40, 50));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(204, 0, 0));
        rSMaterialButtonCircle2.setText("RESET PASSWORD");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 310, 60));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jLabel10.setAlignmentY(0.2F);
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 40));

        lbl_extra.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbl_extra.setForeground(new java.awt.Color(58, 56, 56));
        lbl_extra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_extra.setText("Enter Password...");
        lbl_extra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbl_extraKeyTyped(evt);
            }
        });
        jPanel1.add(lbl_extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 120, 20));

        txt_NewPassReEnter.setBackground(new java.awt.Color(0, 153, 153));
        txt_NewPassReEnter.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_NewPassReEnter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txt_NewPassReEnter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NewPassReEnterKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NewPassReEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 240, 30));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Username");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 180, 80, 20));

        lbl_extra1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbl_extra1.setForeground(new java.awt.Color(58, 56, 56));
        lbl_extra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_extra1.setText("Enter Password...");
        lbl_extra1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lbl_extra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbl_extra1KeyTyped(evt);
            }
        });
        jPanel1.add(lbl_extra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 120, 20));

        txt_NewPass.setBackground(new java.awt.Color(0, 153, 153));
        txt_NewPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_NewPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txt_NewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NewPassKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 240, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Enter New Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 140, 20));

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewjframePackage/icons8_Secure_50px.png"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost

    }//GEN-LAST:event_txt_nameFocusLost

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        if (forgotPassword()) {
            NewLogin lg = new NewLogin();
            lg.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        NewLogin lg = new NewLogin();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txt_NewPassReEnterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NewPassReEnterKeyTyped
        lbl_extra.setText("");
    }//GEN-LAST:event_txt_NewPassReEnterKeyTyped

    private void txt_NewPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NewPassKeyTyped
        lbl_extra1.setText("");
    }//GEN-LAST:event_txt_NewPassKeyTyped

    private void lbl_extraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_extraKeyTyped

    }//GEN-LAST:event_lbl_extraKeyTyped

    private void lbl_extra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_extra1KeyTyped

    }//GEN-LAST:event_lbl_extra1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_extra;
    private javax.swing.JLabel lbl_extra1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private javax.swing.JPasswordField txt_NewPass;
    private javax.swing.JPasswordField txt_NewPassReEnter;
    private app.bolivia.swing.JCTextField txt_contact;
    private app.bolivia.swing.JCTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
